import type { Metadata } from "next"
import { DM_Sans } from "next/font/google"
import "./globals.css"
import { NuqsAdapter } from "nuqs/adapters/next/app"
import { TRPCReactProvider } from "@/trpc/client"
import { Toaster } from "@/components/ui/sonner"

const dm_sans = DM_Sans({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Funroad Marketplace",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${dm_sans.className} antialiased`}>
        <NuqsAdapter>
          <TRPCReactProvider>
            {children}
            <Toaster
              richColors
              position="top-center"
            />
          </TRPCReactProvider>
        </NuqsAdapter>
      </body>
    </html>
  )
}
